# Introduccion a Numpy


In [9]:
import numpy as np

a = np.arange(15).reshape(3,5)
print(a)
print(a.shape)
print(a.size)
print(a.ndim)
print(a.dtype)

type(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
(3, 5)
15
2
int64


numpy.ndarray

In [10]:
import numpy as np
a = np.array([2.4,3,4])
print(a)
print(a.shape)
print(a.size)
print(a.ndim)
print(a.dtype)

[2.4 3.  4. ]
(3,)
3
1
float64


In [16]:
import numpy as np
a = np.array([ [1,2,3] , [4,"fnfln",6] ])
print(a)
print(a.shape)
print(a.size)
print(a.ndim)
print(a.dtype)
      

[['1' '2' '3']
 ['4' 'fnfln' '6']]
(2, 3)
6
2
<U21


In [18]:
import numpy as np
c= np.array([ [1,2,3] , [4,5,6] ] , dtype=complex)
print(c)
print(c.shape)
print(c.size)
print(c.ndim)
print(c.dtype)

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]
(2, 3)
6
2
complex128


In [24]:
import numpy as np

ceros = np.zeros((3,4))
print(ceros)
print(type(ceros))
unos = np.ones((3,4), dtype = np.int16)
print(unos)
print(type(ceros))
aleatorio = np.empty((2,3))
print(aleatorio)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<class 'numpy.ndarray'>
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
<class 'numpy.ndarray'>
[[1.39069238e-309 1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309 1.39069238e-309]]


In [31]:
import numpy as np

metodo_arange = np.arange(10,30,5) #Comienza en 10 termina en 30 y va de 5 en 5.
print(metodo_arange)
print(type(metodo_arange))
metodo_arange_float = np.arange(0,2,0.3) #Comienza en 0 va hasta 2 y va de 0.3 en 0.3.
print(metodo_arange_float)

metodo_range = range(10,30,5)
metodo_range = np.array(metodo_arange)
print(metodo_range)
print(type(metodo_range))

[10 15 20 25]
<class 'numpy.ndarray'>
[0.  0.3 0.6 0.9 1.2 1.5 1.8]
[10 15 20 25]
<class 'numpy.ndarray'>


In [32]:
import numpy as np
from numpy import pi
metodo_linspace = np.linspace(0,2,9) # nueve numeros entre 0 y 2
print(metodo_linspace)
x = np.linspace(0,2*pi,100) # evaluar la funcion x en seno
print(x)
f = np.sin(x)
print(f)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
[0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.26772102
 5.33118753 5.394

In [36]:

a = np.arange(6)                    # array de una dimension
print(a)
b = np.arange(12).reshape(4, 3)     # array de dos dimensiones
print(b,"\n")
c = np.arange(24).reshape(2, 3, 4)  # 3 array de tres dimensiones
print(c)


[0 1 2 3 4 5]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [37]:
print(np.arange(10000))
print(np.arange(10000).reshape(100,100))

[   0    1    2 ... 9997 9998 9999]
[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [43]:
a = np.array([20,30,40,50])
b = np.arange(4)
print(b)
c = a-b
print(c)
b = b**2
print(b)
seno = 10* np.sin(a)
print(seno)
condicion = a < 35
print(condicion)

[0 1 2 3]
[20 29 38 47]
[0 1 4 9]
[ 9.12945251 -9.88031624  7.4511316  -2.62374854]
[ True  True False False]


In [46]:
A = np.array([[1,1] , [0,1]])
B = np.array( [ [2,0] ,[3,4]])
C = A*B
print(C)
D = A @ B
print(D)

M = A.dot(B)
print(M)

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]
